
GIT_DIR := .git

all: 
	$(MAKE) -f admin/Makefile.common cvs

dist:
	$(MAKE) -f admin/Makefile.common dist

ChangeLog: $(GIT_DIR)
	GIT_DIR="$(GIT_DIR)" git log --summary --name-status > ChangeLog

.SILENT:
