Document: kcheckgmail
Title: Debian kcheckgmail Manual
Author: <insert document author here>
Abstract: This manual describes what kcheckgmail is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kcheckgmail/kcheckgmail.sgml.gz

Format: postscript
Files: /usr/share/doc/kcheckgmail/kcheckgmail.ps.gz

Format: text
Files: /usr/share/doc/kcheckgmail/kcheckgmail.text.gz

Format: HTML
Index: /usr/share/doc/kcheckgmail/html/index.html
Files: /usr/share/doc/kcheckgmail/html/*.html

  
